[forest]
trees = ["trees", "localcharts/forest/trees", "bci/stages", "stacks-trees", "skill-trees"]
assets = ["assets", "localcharts/forest/assets"]
url = "https://bci.horse/"
home = "output"
root = "bcf-0001"
